# Comprehensive Makefile System
# Generated by Beast Mode Framework
# Date: 2025-01-27

# Default target
.DEFAULT_GOAL := help

# Phony targets declaration
.PHONY: help discover-system validate-safety optimize-performance test-system validate-targets lint-makefiles generate-reports
.PHONY: observatory-start observatory-stop observatory-status observatory-health observatory-deploy observatory-logs
.PHONY: beast-test beast-compliance beast-fix beast-metrics beast-deploy beast-validate-all
.PHONY: dag-validate dag-execute dag-monitor dag-status
.PHONY: infra-deploy infra-monitor infra-validate infra-backup infra-status infra-health
.PHONY: dev-test dev-lint dev-format dev-validate governance-scan governance-status governance-report
.PHONY: clean-all backup-all restore-all

# =============================================================================
# HELP SYSTEM
# =============================================================================

help: ## Show available targets and usage information
	@echo 'Comprehensive Makefile System - Available Targets:'
	@echo ''
	@echo 'System Discovery & Validation:'
	@echo '  make discover-system         - Discover all system capabilities'
	@echo '  make validate-safety         - Validate system safety'
	@echo '  make validate-targets        - Validate all Makefile targets'
	@echo '  make test-system            - Run comprehensive system tests'
	@echo ''
	@echo 'Observatory System:'
	@echo '  make observatory-deploy      - Deploy Observatory system'
	@echo '  make observatory-start       - Start Observatory services'
	@echo '  make observatory-stop        - Stop Observatory services'
	@echo '  make observatory-status      - Check Observatory status'
	@echo '  make observatory-health      - Check Observatory health'
	@echo '  make observatory-logs        - View Observatory logs'
	@echo ''
	@echo 'Beast Mode Framework:'
	@echo '  make beast-deploy           - Deploy Beast Mode framework'
	@echo '  make beast-test             - Run Beast Mode tests'
	@echo '  make beast-compliance       - Check Beast Mode compliance'
	@echo '  make beast-fix              - Fix Beast Mode issues'
	@echo '  make beast-metrics          - Generate Beast Mode metrics'
	@echo '  make beast-validate-all     - Validate Beast Mode framework'
	@echo ''
	@echo 'DAG Orchestration:'
	@echo '  make dag-validate           - Validate DAG structure'
	@echo '  make dag-execute            - Execute DAG workflow'
	@echo '  make dag-monitor            - Monitor DAG execution'
	@echo '  make dag-status             - Check DAG status'
	@echo ''
	@echo 'Infrastructure Management:'
	@echo '  make infra-deploy           - Deploy infrastructure'
	@echo '  make infra-monitor          - Monitor infrastructure'
	@echo '  make infra-validate         - Validate infrastructure'
	@echo '  make infra-backup           - Backup infrastructure'
	@echo '  make infra-status           - Check infrastructure status'
	@echo '  make infra-health           - Check infrastructure health'
	@echo ''
	@echo 'Development Workflow:'
	@echo '  make dev-test               - Run development tests'
	@echo '  make dev-lint               - Lint code'
	@echo '  make dev-format             - Format code'
	@echo '  make dev-validate           - Validate development setup'
	@echo ''
	@echo 'Governance & Quality:'
	@echo '  make governance-scan        - Scan for orphaned solutions'
	@echo '  make governance-status      - Check governance status'
	@echo '  make governance-report      - Generate governance report'
	@echo '  make lint-makefiles         - Lint all Makefiles'
	@echo ''
	@echo 'System Operations:'
	@echo '  make generate-reports       - Generate all system reports'
	@echo '  make optimize-performance   - Optimize system performance'
	@echo '  make clean-all              - Clean all artifacts'
	@echo '  make backup-all             - Backup all data'
	@echo '  make restore-all            - Restore from backup'
	@echo ''
	@echo 'For more information, see: docs/makefile_system_guide.md'

# =============================================================================
# SYSTEM DISCOVERY & VALIDATION
# =============================================================================

discover-system: ## Discover all system capabilities
	@echo '� Disctovering system capabilities...'
	python scripts/makefile_system_discovery.py --verbose
	@echo '✅ System discovery complete'

validate-safety: ## Validate system safety
	@echo '🛡️ Validating system safety...'
	python scripts/makefile_safety_validator.py system
	@echo '✅ Safety validation complete'

validate-targets: ## Validate all Makefile targets
	@echo '🎯 Validating Makefile targets...'
	python scripts/validate_makefile_targets.py
	@echo '✅ Target validation complete'

test-system: ## Run comprehensive system tests
	@echo '🧪 Running comprehensive system tests...'
	python scripts/test_makefile_system.py
	@echo '✅ System tests complete'

optimize-performance: ## Optimize system performance
	@echo '⚡ Optimizing system performance...'
	python scripts/makefile_performance_optimizer.py --report
	@echo '✅ Performance optimization complete'

lint-makefiles: ## Lint all Makefiles
	@echo '📋 Linting all Makefiles...'
	python scripts/lint_makefile.py
	@echo '✅ Makefile linting complete'

# =============================================================================
# OBSERVATORY SYSTEM
# =============================================================================

observatory-deploy: ## Deploy Observatory system
	@echo '🔭 Deploying Observatory system...'
	python src/makefile_governance/integration/observatory_integration.py --generate-makefile makefiles/observatory.mk
	$(MAKE) -f makefiles/observatory.mk observatory-deploy
	@echo '✅ Observatory system deployed'

observatory-start: ## Start Observatory services in Docker containers
	@echo '🔭 Starting Observatory services in containers...'
	python scripts/deploy_observatory.py
	@echo '✅ Observatory services started'

observatory-stop: ## Stop Observatory services and containers
	@echo '🔭 Stopping Observatory services and containers...'
	python scripts/stop_observatory.py
	@echo '✅ Observatory services stopped'

observatory-restart: ## Restart Observatory services
	@echo '🔭 Restarting Observatory services...'
	$(MAKE) observatory-stop
	sleep 5
	$(MAKE) observatory-start
	@echo '✅ Observatory services restarted'

observatory-build: ## Build Observatory Docker images
	@echo '🔭 Building Observatory Docker images...'
	cd deployment/observatory && docker-compose build
	@echo '✅ Observatory images built'

observatory-shell: ## Access Observatory container shell
	@echo '🔭 Accessing Observatory container shell...'
	docker exec -it beast-mode-observatory /bin/bash

observatory-status: ## Check Observatory status
	@echo '🔭 Checking Observatory status...'
	python src/makefile_governance/integration/observatory_integration.py --status
	@echo '✅ Observatory status check complete'

observatory-health: ## Check Observatory health
	@echo '🔭 Checking Observatory health...'
	@echo 'Local services:'
	@curl -s http://localhost:8888/health || echo '❌ Observatory health check failed'
	@curl -s http://localhost:9090/-/healthy || echo '❌ Prometheus health check failed'
	@curl -s http://localhost:3000/api/health || echo '❌ Grafana health check failed'
	@echo ''
	@echo 'Tunnel endpoints:'
	@curl -s https://observatory.nkllon.com/health || echo '❌ Observatory tunnel failed'
	@curl -s https://prometheus.nkllon.com/-/healthy || echo '❌ Prometheus tunnel failed'
	@curl -s https://grafana.nkllon.com/api/health || echo '❌ Grafana tunnel failed'
	@echo '✅ Observatory health check complete'

observatory-restart-services: ## Restart Observatory services (Docker containers)
	@echo '🔭 Restarting Observatory services...'
	@docker start prometheus || echo 'Prometheus start failed'
	@docker start grafana-public || echo 'Grafana start failed'
	@echo '✅ Observatory services restarted'

observatory-restart-tunnel: ## Restart Cloudflare tunnel
	@echo '🔭 Restarting Cloudflare tunnel...'
	@pkill -f "cloudflared tunnel" || echo 'No tunnel to kill'
	@sleep 2
	@cloudflared tunnel --config cloudflared-config.yml run &
	@echo '✅ Cloudflare tunnel restarted'

observatory-logs: ## View Observatory container logs
	@echo '🔭 Observatory Container Logs:'
	@echo '============================'
	@docker logs beast-mode-observatory --tail=50 2>/dev/null || echo 'Observatory container not running'
	@docker logs observatory-prometheus --tail=20 2>/dev/null || echo 'Prometheus container not running'
	@docker logs observatory-grafana --tail=20 2>/dev/null || echo 'Grafana container not running'

# =============================================================================
# BEAST MODE FRAMEWORK
# =============================================================================

beast-deploy: ## Deploy Beast Mode framework
	@echo '🐺 Deploying Beast Mode framework...'
	python src/makefile_governance/integration/beast_mode_integration.py --generate-makefile makefiles/beast_mode.mk
	$(MAKE) -f makefiles/beast_mode.mk beast-deploy
	@echo '✅ Beast Mode framework deployed'

beast-test: ## Run Beast Mode tests
	@echo '🐺 Running Beast Mode tests...'
	python -m pytest tests/unit/beast_mode/ -v --tb=short
	@echo '✅ Beast Mode tests complete'

beast-compliance: ## Check Beast Mode compliance
	@echo '🐺 Running Beast Mode compliance checks...'
	python scripts/check_reflective_module_compliance.py || echo 'Compliance check attempted'
	python scripts/check_beast_mode_patterns.py || echo 'Pattern check attempted'
	@echo '✅ Beast Mode compliance check complete'

beast-fix: ## Fix Beast Mode issues
	@echo '� Fixling Beast Mode issues...'
	python scripts/auto_fix_beast_mode_issues.py || echo 'Auto-fix attempted'
	$(MAKE) beast-validate-all
	@echo '✅ Beast Mode issues fixed'

beast-metrics: ## Generate Beast Mode metrics
	@echo '🐺 Generating Beast Mode metrics...'
	python scripts/generate_beast_mode_dashboard.py || echo 'Metrics generation attempted'
	@echo '✅ Beast Mode metrics generated'

beast-validate-all: ## Validate Beast Mode framework
	@echo '🐺 Validating Beast Mode framework...'
	python scripts/validate_beast_mode_framework.py || echo 'Validation attempted'
	@echo '✅ Beast Mode framework validation complete'

# =============================================================================
# DAG ORCHESTRATION
# =============================================================================

dag-validate: ## Validate DAG structure
	@echo '🔄 Validating DAG structure...'
	python scripts/infrastructure_task_dag_validator.py || echo 'DAG validation attempted'
	@echo '✅ DAG validation complete'

dag-execute: ## Execute DAG workflow
	@echo '🔄 Executing DAG workflow...'
	python scripts/infrastructure_governance_orchestrator.py --execute-next || echo 'DAG execution attempted'
	@echo '✅ DAG workflow execution complete'

dag-monitor: ## Monitor DAG execution
	@echo '🔄 Monitoring DAG execution...'
	python scripts/dag_execution_monitor.py || echo 'DAG monitoring attempted'
	@echo '✅ DAG monitoring complete'

dag-status: ## Check DAG status
	@echo '🔄 Checking DAG status...'
	python scripts/check_dag_status.py || echo 'DAG status check attempted'
	@echo '✅ DAG status check complete'

# =============================================================================
# INFRASTRUCTURE MANAGEMENT
# =============================================================================

infra-deploy: ## Deploy infrastructure
	@echo '🏗️ Deploying infrastructure...'
	python src/makefile_governance/integration/infrastructure_integration.py --generate-makefile makefiles/infrastructure.mk
	$(MAKE) -f makefiles/infrastructure.mk infra-deploy-all
	@echo '✅ Infrastructure deployment complete'

infra-monitor: ## Monitor infrastructure
	@echo '🏗️ Starting infrastructure monitoring...'
	python scripts/start_infrastructure_monitoring.py || echo 'Infrastructure monitoring attempted'
	@echo '✅ Infrastructure monitoring started'

infra-validate: ## Validate infrastructure
	@echo '🏗️ Validating infrastructure configuration...'
	python scripts/validate_infrastructure_config.py || echo 'Infrastructure validation attempted'
	@echo '✅ Infrastructure validation complete'

infra-backup: ## Backup infrastructure
	@echo '🏗️ Backing up infrastructure data...'
	python scripts/backup_infrastructure_configs.py || echo 'Infrastructure backup attempted'
	@echo '✅ Infrastructure backup complete'

infra-status: ## Check infrastructure status
	@echo '🏗️ Checking infrastructure status...'
	python src/makefile_governance/integration/infrastructure_integration.py --status
	@echo '✅ Infrastructure status check complete'

infra-health: ## Check infrastructure health
	@echo '🏗️ Checking infrastructure health...'
	@lsof -i:6379 >/dev/null 2>&1 && echo '✅ Redis is running' || echo '❌ Redis is not running'
	@lsof -i:5432 >/dev/null 2>&1 && echo '✅ PostgreSQL is running' || echo '❌ PostgreSQL is not running'
	@lsof -i:9090 >/dev/null 2>&1 && echo '✅ Prometheus is running' || echo '❌ Prometheus is not running'
	@echo '✅ Infrastructure health check complete'

# =============================================================================
# DEVELOPMENT WORKFLOW
# =============================================================================

dev-test: ## Run development tests
	@echo '🧪 Running development tests...'
	python -m pytest tests/ -v --tb=short
	@echo '✅ Development tests complete'

dev-lint: ## Lint code
	@echo '📋 Linting code...'
	python -m flake8 src/ --max-line-length=120
	python -m mypy src/ --ignore-missing-imports
	@echo '✅ Code linting complete'

dev-format: ## Format code
	@echo '💅 Formatting code...'
	python -m black src/ --line-length=120
	python -m isort src/
	@echo '✅ Code formatting complete'

dev-validate: ## Validate development setup
	@echo '🔍 Validating development setup...'
	python scripts/validate_development_environment.py || echo 'Development validation attempted'
	@echo '✅ Development setup validation complete'

# =============================================================================
# GOVERNANCE & QUALITY
# =============================================================================

governance-scan: ## Scan for orphaned solutions
	@echo '🔍 Running semantic orphaned solution scan...'
	python scripts/semantic_orphaned_scanner.py
	@echo '✅ Governance scan complete'

governance-status: ## Check governance status
	@echo '📊 Checking governance system status...'
	python scripts/background_governance_scheduler.py --status
	@echo '✅ Governance status check complete'

governance-report: ## Generate governance report
	@echo '📋 Generating governance report...'
	python scripts/background_governance_scheduler.py --run orphaned_solution_scan
	@echo '✅ Governance report generated'

# =============================================================================
# SYSTEM OPERATIONS
# =============================================================================

generate-reports: ## Generate all system reports
	@echo '📊 Generating all system reports...'
	python scripts/makefile_system_discovery.py --output reports/discovery.json
	python scripts/test_makefile_system.py --report reports/test_results.json
	python scripts/validate_makefile_targets.py --report reports/validation.json
	python scripts/lint_makefile.py --report reports/lint.json
	@echo '✅ All reports generated'

clean-all: ## Clean all artifacts
	@echo '🧹 Cleaning all artifacts...'
	rm -rf build/ dist/ *.egg-info/
	rm -rf .pytest_cache/ .coverage htmlcov/
	rm -rf reports/*.json reports/*.html
	find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
	find . -type f -name "*.pyc" -delete
	@echo '✅ All artifacts cleaned'

backup-all: ## Backup all data
	@echo '💾 Backing up all data...'
	mkdir -p backups/$(shell date +%Y%m%d_%H%M%S)
	cp -r .kiro/ backups/$(shell date +%Y%m%d_%H%M%S)/
	cp -r config/ backups/$(shell date +%Y%m%d_%H%M%S)/ 2>/dev/null || true
	cp -r data/ backups/$(shell date +%Y%m%d_%H%M%S)/ 2>/dev/null || true
	@echo '✅ All data backed up'

restore-all: ## Restore from backup
	@echo '🔄 Restoring from backup...'
	python scripts/restore_system_backup.py || echo 'Restore attempted'
	@echo '✅ System restore complete'

# =============================================================================
# TESTING TARGETS
# =============================================================================

test-makefile-quick: ## Quick smoke test for Makefile system
	@echo '💨 Running quick Makefile smoke tests...'
	python scripts/test_makefile_system.py --type unit
	@echo '✅ Quick tests complete'

test-makefile-comprehensive: ## Run comprehensive Makefile tests
	@echo '🧪 Running comprehensive Makefile tests...'
	python scripts/orchestrate_makefile_unit_tests.py
	@echo '✅ Comprehensive tests complete'

test-makefile-parallel: ## Run tests in parallel with detailed output
	@echo '⚡ Running parallel Makefile tests...'
	python -m pytest tests/unit/makefile_governance/ -v -n auto --tb=short
	@echo '✅ Parallel tests complete'

# =============================================================================
# INCLUDE MODULAR TARGETS
# =============================================================================

# Include governance targets
-include makefiles/governance.mk

# Include testing targets  
-include makefiles/testing.mk

# Include generated targets (if they exist)
-include .make-tasks/generated-targets.mk

# =============================================================================
# LEGACY COMPATIBILITY
# =============================================================================

# Maintain compatibility with legacy targets
install: ## Install dependencies (legacy compatibility)
	@echo "🔧 Installing dependencies..."
	pip install -r requirements.txt
	@echo "✅ Installation complete"

deploy: ## Deploy system (legacy compatibility)
	@echo "🚀 Deploying system..."
	$(MAKE) observatory-deploy
	$(MAKE) beast-deploy
	$(MAKE) infra-deploy
	@echo "✅ System deployment complete"

verify: ## Verify system (legacy compatibility)
	@echo "🔍 Verifying system..."
	$(MAKE) validate-targets
	$(MAKE) test-system
	@echo "✅ System verification complete"

test: ## Run tests (legacy compatibility)
	@echo "🧪 Running tests..."
	$(MAKE) test-system
	@echo "✅ Tests complete"

clean: ## Clean artifacts (legacy compatibility)
	@echo "🧹 Cleaning artifacts..."
	$(MAKE) clean-all
	@echo "✅ Cleaning complete"