global:
  evaluation_interval: 15s
  scrape_interval: 15s
scrape_configs:
- job_name: observatory
  metrics_path: /metrics
  scrape_interval: 10s
  static_configs:
  - targets:
    - observatory:8888
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
