global:
  evaluation_interval: 15s
  external_labels:
    datacenter: home
    instance_id: vonnegut
  scrape_interval: 15s
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: observatory
  metrics_path: /metrics
  scrape_interval: 5s
  static_configs:
  - targets:
    - observatory-app:8888
- job_name: redis
  metrics_path: /metrics
  scrape_interval: 30s
  static_configs:
  - targets:
    - observatory-redis:6379
- job_name: grafana
  metrics_path: /metrics
  scrape_interval: 30s
  static_configs:
  - targets:
    - observatory-grafana:3000
- job_name: node-exporter
  metrics_path: /metrics
  scrape_interval: 30s
  static_configs:
  - targets:
    - host.docker.internal:9100
