"""
Report Generator Utils

This module was extracted from report_generator.py
as part of RM-DDD compliance refactoring.
"""

from typing import List, Dict, Any, Optional
from datetime import datetime
from dataclasses import dataclass
import json
from ..interfaces import ComplianceReporter
from ..models import ComplianceAnalysisResult, ComplianceIssue, IssueSeverity, ComplianceIssueType, RemediationStep, Phase2ValidationResult
from src.rm_ddd.core.health import ModuleHealth


class GetreportformatClass:
    """Auto-generated class for functions."""

    def get_report_format(self) -> str:
    """Get the format of reports generated by this reporter."""
    return self.report_format

    def _format_complete_report(self, report_id: str, analysis_result: ComplianceAnalysisResult, executive_summary: str, detailed_findings: Dict[str, Any], remediation_plan: List[RemediationStep], phase3_assessment: Dict[str, Any]) -> str:
    """Format the complete compliance report as markdown."""
    report_sections = [f'# Beast Mode Framework Compliance Report', f'**Report ID:** {report_id}', f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", '', executive_summary, '', '## Detailed Findings', '', self._format_detailed_findings(detailed_findings), '', '## Remediation Plan', '', self._format_remediation_plan(remediation_plan), '', '## Phase 3 Readiness Assessment', '', self._format_phase3_assessment(phase3_assessment), '', '## Appendix', '', self._format_appendix(analysis_result)]
    return '\n'.join(report_sections)

    def _format_detailed_findings(self, findings: Dict[str, Any]) -> str:
    """Format detailed findings section."""
    sections = []
    for category, data in findings.items():
    section_title = category.replace('_', ' ').title()
    sections.append(f'### {section_title}')
    if isinstance(data, dict):
    for key, value in data.items():
    if isinstance(value, (list, tuple)) and len(value) > 0:
    sections.append(f"- **{key.replace('_', ' ').title()}:** {len(value)} items")
    if len(value) <= 5:
    for item in value:
    sections.append(f'  - {item}')
    else:
    for item in value[:3]:
    sections.append(f'  - {item}')
    sections.append(f'  - ... and {len(value) - 3} more')
    else:
    sections.append(f"- **{key.replace('_', ' ').title()}:** {value}")
    sections.append('')
    return '\n'.join(sections)

    def _format_remediation_plan(self, remediation_plan: List[RemediationStep]) -> str:
    """Format remediation plan section."""
    if not remediation_plan:
    return 'No remediation steps required.'
    sections = []
    for i, step in enumerate(remediation_plan, 1):
    sections.extend([f'### {step.step_id}: {step.description}', f'- **Priority:** {step.priority.value.title()}', f'- **Estimated Effort:** {step.estimated_effort}', f'- **Affected Components:** {len(step.affected_components)} files'])
    if step.prerequisites:
    sections.append('- **Prerequisites:**')
    for prereq in step.prerequisites:
    sections.append(f'  - {prereq}')
    if step.validation_criteria:
    sections.append('- **Validation Criteria:**')
    for criteria in step.validation_criteria:
    sections.append(f'  - {criteria}')
    sections.append('')
    return '\n'.join(sections)

    def _format_phase3_assessment(self, assessment: Dict[str, Any]) -> str:
    """Format Phase 3 readiness assessment section."""
    sections = [f"**Overall Readiness Score:** {assessment['overall_readiness_score']:.1f}/100.0", f"**Phase 3 Ready:** {('✅ YES' if assessment['phase3_ready'] else '❌ NO')}", '', '### Readiness Factors']
    for factor, data in assessment['readiness_factors'].items():
    factor_title = factor.replace('_', ' ').title()
    status_emoji = '✅' if data['status'] == 'PASS' else '❌'
    sections.append(f"- **{factor_title}:** {status_emoji} {data['status']}")
    sections.extend(['', '### Recommendations'])
    for rec in assessment['recommendations']:
    sections.append(f'- {rec}')
    sections.extend(['', '### Next Steps'])
    for step in assessment['next_steps']:
    sections.append(f'1. {step}')
    return '\n'.join(sections)

    def _format_appendix(self, analysis_result: ComplianceAnalysisResult) -> str:
    """Format appendix with technical details."""
    sections = ['### Technical Details', f'- Analysis Timestamp: {analysis_result.analysis_timestamp}', f'- Commits Analyzed: {len(analysis_result.commits_analyzed)}', f'- Overall Compliance Score: {analysis_result.overall_compliance_score:.2f}', '', '### Issue Summary by Severity']
    all_issues = self._collect_all_issues(analysis_result)
    severity_counts = {}
    for issue in all_issues:
    severity_counts[issue.severity] = severity_counts.get(issue.severity, 0) + 1
    for severity in IssueSeverity:
    count = severity_counts.get(severity, 0)
    sections.append(f'- {severity.value.title()}: {count}')
    return '\n'.join(sections)

    def register_module(self, registry):
    """Register module with registry."""
    metadata = self.get_interface_metadata()
    if hasattr(registry, 'register'):
    registry.register(metadata)

    def get_interface_metadata(self):
    """Get interface metadata for registry."""
    return {
    'module_id': getattr(self, 'module_id', self.__class__.__name__),
    'interface_type': self.__class__.__name__,
    'version': '1.0.0',
    'dependencies': [],
    'capabilities': []
    }

