services:
  grafana:
    environment:
      GF_SESSION_PROVIDER_CONFIG: addr=observatory-redis:6379,pool_size=100,db=1
  observatory:
    environment:
      DOCKER_DESKTOP: 'false'
      GRAFANA_URL: http://observatory-grafana:3000
      JAEGER_ENDPOINT: http://observatory-jaeger:14268/api/traces
      PROMETHEUS_URL: http://observatory-prometheus:9090
      REDIS_HOST: observatory-redis
version: '3.8'
