from .anticorruption_handlers_part_1 import *
from .anticorruption_handlers_part_2 import *
from .anticorruption_handlers_part_3 import *
from .anticorruption_handlers_part_4 import *
from .anticorruption_handlers_part_5 import *
from .anticorruption_handlers_part_6 import *
from .anticorruption_handlers_part_7 import *
from .anticorruption_handlers_part_8 import *
from .anticorruption_handlers_part_9 import *
from .anticorruption_handlers_part_10 import *
from .anticorruption_handlers_part_11 import *
from .anticorruption_handlers_part_12 import *
from .anticorruption_handlers_part_13 import *
from .anticorruption_handlers_part_14 import *
from .anticorruption_handlers_part_15 import *
from src.rm_ddd.core.health import ModuleHealth
