# BLACK FORMATTING FAILED - SYNTAX ERROR
import re
from pathlib import Path
import git
import unified_reflective_module as urm


class HybridCodeGenerator:
    def __init__(self, models):
        self.models = models
        self.urm = urm.UnifiedReflectiveModule()

    async def generate(self, task):
        with self.urm.trace("generate", {"task_id": task.id}):
            model = self.select_model(task)
            code = await model.generate(task.requirements)

            # Record operation metrics
            self.urm.record_metric("total_operations", 1)
            self.urm.record_metric("avg_generation_time_ms", model.last_execution_time)

        return code

    async def review(self, generated_code):
        with self.urm.trace("review"):

            # Review the code for quality and adherence to standards
            result = await self.models["deepseek"].review(generated_code)

            # Record operation metrics
            self.urm.record_metric(
                "avg_review_time_ms", self.models["deepseek"].last_execution_time
            )

        return result

    def select_model(self, task):
        if "claude" in task.requirements:
            return self.models["claude"]
        else:
            return self.models["default"]


class KiroSpecParser:
    def __init__(self):
        self.task_pattern = re.compile(r"^-  \[([ x])\](\*?)\s*(\d+(?:\.\d+)?)\s+(.+)$")

    def parse_tasks_file(self, tasks_path):
        with open(tasks_path, "r") as f:
            content = f.read()

        tasks = []
        current_task = None

        for line in content.split("\n"):
            line = line.strip()

            match = self.task_pattern.match(line)
            if match:
                completed, optional, task_id, description = match.groups()

                if current_task:
                    tasks.append(current_task)

                current_task = {
                    "id": task_id,
                    "description": description,
                    "requirements": [],
                    "dependencies": [],
                    "optional": bool(optional),
                    "metadata": {"completed": completed == "x", "line": line},
                }
            elif current_task and line.startswith("-      "):
                current_task["requirements"].append(line[2:])

        if current_task:
            tasks.append(current_task)

        return tasks

    def load_context_files(self, spec_dir):
        context = {}

        req_path = Path(spec_dir) / "requirements.md"
        if req_path.exists():
            context["requirements"] = req_path.read_text()

        design_path = Path(spec_dir) / "design.md"
        if design_path.exists():
            context["design"] = design_path.read_text()

        return context


class GitIntegration:
    def __init__(self, repo_path):
        self.repo_path = Path(repo_path)
        self.repo = git.Repo(repo_path)

    async def create_feature_branch(self, task_id):
        branch_name = f"hybrid-gen/{task_id}"

        new_branch = self.repo.create_head(branch_name)
        new_branch.checkout()

        return branch_name

    async def commit_generated_code(self, files, task_description):
        for file_path in files:
            self.repo.index.add([file_path])

        commit_message = (
            f"feat: {task_description[:50]}...\n\nGenerated by Hybrid Code Generator"
        )
        self.repo.index.commit(commit_message)


class TaskStatusIntegration:
    def __init__(self, spec_path):
        self.spec_path = Path(spec_path)
        self.tasks_file = self.spec_path / "tasks.md"

    async def update_task_status(self, task_id, status):
        if not self.tasks_file.exists():
            return

        content = self.tasks_file.read_text()

        pattern = rf"^(-  \[)[ x](\].*{re.escape(task_id)}.*)$"
        status_char = "x" if status == "completed" else "      "
        replacement = rf"\1{status_char}\2"

        updated_content = re.sub(pattern, replacement, content, flags=re.MULTILINE)

        self.tasks_file.write_text(updated_content)
