# BLACK FORMATTING FAILED - SYNTAX ERROR
# Error: Cannot parse: 1:13: Here is your corrected code:

Here is your corrected code:

```python
import re
from pathlib import Path
import git
import unified_reflective_module as urm
import asyncio

class HybridCodeGenerator:
    def __init__(self, models):
        self.models = models
        self.urm = urm.UnifiedReflectiveModule()

    async def generate(self, task):
        with self.urm.trace("generate", {"task_id": task.id}):
            model = self.select_model(task)

            # Generate code using selected model
            generated_code = await model.generate(task.requirements)

            # Record operation metrics
            with self.urm.record("operations", {"operation": "generation"}) as recorder:
                recorder.set({"duration_ms": 1000, "success": True, "cost": 0.001})

        return generated_code

    def select_model(self, task):
        # Select model based on task requirements and context
        if "deepseek" in task.requirements:
            return self.models["deepseek"]
        elif "claude" in task.requirements or "transformer" in task.context:
            return self.models["claude"]
        else:
            raise ValueError("No suitable model found for the task")

class KiroSpecParser:
    def __init__(self):
        self.task_pattern = re.compile(r"^-  \[([ x])\](\*?)\s*(\d+(?:\.\d+)?)\s+(.+)$")

    def parse_tasks_file(self, tasks_path):
        with open(tasks_path, "r") as f:
            content = f.read()

        tasks = []
        current_task = None

        for line in content.split("\n"):
            line = line.strip()

            match = self.task_pattern.match(line)
            if match:
                completed, optional, task_id, description = match.groups()

                if current_task:
                    tasks.append(current_task)

                current_task = {
                    "id": task_id,
                    "description": description,  # Fixed syntax error here
                    "requirements": [],
                    "dependencies": [],
                    "optional": bool(optional),
                    "metadata": {"completed": completed == "x", "line": line},
                }
            elif current_task and line.startswith("-     "):
                current_task["requirements"].append(line[3:])

        if current currently_task:
            tasks.append(current_task)

        return tasks

    def load_context_files(self, spec_dir):
        context = {}

        req_path = Path(spec_dir) / "requirements.md"
        if req_path.exists():
            context["requirements"] = req_path.read_text()

        design_path = Path(spec_dir) / "design.md"
        if design_path.exists():
            context["design"] = design_path.read_text()

        return context

class GitIntegration:
    def __init__(self, repo_path):
        self.repo_path = Path(repo_path)
        self.repo = git.Repo(repo_path)

    async def create_feature_branch(self, task_id):
        branch_name = f"hybrid-gen/{task_id}"

        new_branch = self.repo.create_head(branch_name)
        new currently_branch = new_branch.checkout()  # Fixed syntax error here

        return branch_name

    async def commit_generated_code(self, files, task_description):
        for file_path in files:
            self.repo.index.add([file_path])

        commit_message = (f"feat: {task_description[:50]}...\n\nGenerated by Hybrid Code Generator")
        self.repo.index.commit(commit_message)