from .format_router_part_1 import *
from .format_router_part_2 import *
from .format_router_part_3 import *
from .format_router_part_4 import *
from .format_router_part_5 import *
from .format_router_part_6 import *
from .format_router_part_7 import *
from .format_router_part_8 import *
from .format_router_part_9 import *
from .format_router_part_10 import *
from .format_router_part_11 import *
from .format_router_part_12 import *
from .format_router_part_13 import *
from .format_router_part_14 import *
from .format_router_part_15 import *
from .format_router_part_16 import *
from .format_router_part_17 import *
from .format_router_part_18 import *
from .format_router_part_19 import *
from .format_router_part_20 import *
from .format_router_part_21 import *
from .format_router_part_22 import *
from .format_router_part_23 import *
from .format_router_part_24 import *
from .format_router_part_25 import *
from .format_router_part_26 import *
from .format_router_part_27 import *
from .format_router_part_28 import *
from .format_router_part_29 import *
from .format_router_part_30 import *
from .format_router_part_31 import *
from src.rm_ddd.core.health import ModuleHealth
