#!/usr/bin/env python3
"""
Auto-generated CLI for makefile_health_manager
Generated by RM-DDD CLI Generator Engine
Version: 1.0.0
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, Any, List

# Add project root to path for imports
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from src.rm_ddd.core.unified_reflective_module import ReflectiveModule, ModuleCapability, ModuleStatus


class MakefileHealthManagerCLI:
    """Auto-generated CLI for makefile_health_manager"""
    
    def __init__(self):
        self.module = None
        self.setup_module()
    
    def setup_module(self):
        """Initialize the module instance"""
        try:
            # Import and instantiate the module
            from src.rc1.foundation.makefile_health_manager import MakefileHealthManager
            self.module = MakefileHealthManager()
        except Exception as e:
            print(f"Error initializing module: {e}", file=sys.stderr)
            sys.exit(1)
    
    def handle_stdin_input(self) -> Dict[str, Any]:
        """Handle stdin input processing - REQ-CLI-016 to REQ-CLI-030"""
        if sys.stdin.isatty():
            return {}
        
        try:
            # Try to read JSON from stdin
            input_data = sys.stdin.read().strip()
            if input_data:
                return json.loads(input_data)
        except json.JSONDecodeError:
            # If not JSON, treat as text
            return {"text_input": input_data}
        except Exception as e:
            print(f"Error processing stdin: {e}", file=sys.stderr)
            return {}
        
        return {}
    
    def output_json(self, data: Dict[str, Any]):
        """Output data as JSON to stdout - REQ-CLI-021 to REQ-CLI-025"""
        print(json.dumps(data, indent=2, default=str))
    
    def output_text(self, text: str):
        """Output text to stdout"""
        print(text)
    
    def output_error(self, message: str):
        """Output error to stderr"""
        print(f"Error: {message}", file=sys.stderr)
    
    def help_command(self):
        """Show help information - REQ-CLI-031"""
        help_text = f"""
makefile_health_manager CLI - Auto-generated command-line interface

Version: 1.0.0
Module: MakefileHealthManager

Standard Commands:
  --help, -h          Show this help message
  --version, -v       Show version information
  --status            Show module status
  --health            Show module health
  --capabilities      Show module capabilities
  --info              Show module information
  --config            Show module configuration
  --metrics           Show module metrics
  --reset             Reset module state

Capability Commands:
Method Commands:
Stdin/Stdout Support:
  - Supports JSON input via stdin
  - Supports text input via stdin
  - Outputs JSON or text to stdout
  - Errors output to stderr

Examples:
  echo '{"action": "status"}' | makefile_health_manager --status
  makefile_health_manager --capabilities | jq '.capabilities'
  makefile_health_manager --health --format json
"""
        self.output_text(help_text)
    
    def version_command(self):
        """Show version information - REQ-CLI-032"""
        version_info = {
            "module_id": "makefile_health_manager",
            "version": "1.0.0",
            "module_class": "MakefileHealthManager",
            "generated_at": "2025-09-16T20:06:54.876600"
        }
        self.output_json(version_info)
    
    def status_command(self):
        """Show module status - REQ-CLI-033"""
        try:
            health = self.module.get_health_status()
            status_info = {
                "module_id": health.module_id,
                "status": health.status.value,
                "health_score": health.health_score,
                "uptime_seconds": health.uptime_seconds,
                "error_count": health.error_count,
                "warning_count": health.warning_count,
                "last_check": health.last_check.isoformat(),
                "issues": health.issues
            }
            self.output_json(status_info)
        except Exception as e:
            self.output_error(f"Failed to get status: {e}")
    
    def health_command(self):
        """Show module health - REQ-CLI-034"""
        try:
            health = self.module.get_health_status()
            health_info = {
                "module_id": health.module_id,
                "status": health.status.value,
                "health_score": health.health_score,
                "uptime_seconds": health.uptime_seconds,
                "error_count": health.error_count,
                "warning_count": health.warning_count,
                "last_check": health.last_check.isoformat(),
                "issues": health.issues
            }
            self.output_json(health_info)
        except Exception as e:
            self.output_error(f"Failed to get health: {e}")
    
    def capabilities_command(self):
        """Show module capabilities - REQ-CLI-035"""
        try:
            capabilities = self.module.get_capabilities()
            capabilities_info = {
                "module_id": "makefile_health_manager",
                "capabilities": [cap.value for cap in capabilities],
                "capability_count": len(capabilities)
            }
            self.output_json(capabilities_info)
        except Exception as e:
            self.output_error(f"Failed to get capabilities: {e}")
    
    def info_command(self):
        """Show module information - REQ-CLI-036"""
        try:
            info = self.module.get_module_info()
            self.output_json(info)
        except Exception as e:
            self.output_error(f"Failed to get info: {e}")
    
    def config_command(self):
        """Show module configuration - REQ-CLI-037"""
        try:
            if hasattr(self.module, 'get_configuration'):
                config = self.module.get_configuration()
                self.output_json(config)
            else:
                self.output_text("Configuration not available for this module")
        except Exception as e:
            self.output_error(f"Failed to get configuration: {e}")
    
    def metrics_command(self):
        """Show module metrics - REQ-CLI-038"""
        try:
            if hasattr(self.module, 'get_prometheus_metrics'):
                metrics = self.module.get_prometheus_metrics()
                self.output_json(metrics)
            else:
                self.output_text("Metrics not available for this module")
        except Exception as e:
            self.output_error(f"Failed to get metrics: {e}")
    
    def reset_command(self):
        """Reset module state - REQ-CLI-040"""
        try:
            if hasattr(self.module, 'reset'):
                self.module.reset()
                self.output_text("Module reset successfully")
            else:
                self.output_text("Reset not available for this module")
        except Exception as e:
            self.output_error(f"Failed to reset module: {e}")
    
    # Capability-based command groups - REQ-CLI-041 to REQ-CLI-045

    # Method-based commands - REQ-CLI-151 to REQ-CLI-155

    def run(self, args: List[str]):
        """Run the CLI with given arguments"""
        parser = argparse.ArgumentParser(
            description=f"makefile_health_manager CLI - Auto-generated command-line interface",
            formatter_class=argparse.RawDescriptionHelpFormatter
        )
        
        # Standard options - REQ-CLI-106 to REQ-CLI-110
        parser.add_argument('--version', '-v', action='store_true', help='Show version information')
        parser.add_argument('--status', action='store_true', help='Show module status')
        parser.add_argument('--health', action='store_true', help='Show module health')
        parser.add_argument('--capabilities', action='store_true', help='Show module capabilities')
        parser.add_argument('--info', action='store_true', help='Show module information')
        parser.add_argument('--config', action='store_true', help='Show module configuration')
        parser.add_argument('--metrics', action='store_true', help='Show module metrics')
        parser.add_argument('--reset', action='store_true', help='Reset module state')
        
        # Capability commands

        # Method commands

        # Parse arguments
        parsed_args = parser.parse_args(args)
        
        # Handle stdin input - REQ-CLI-111 to REQ-CLI-115
        stdin_data = self.handle_stdin_input()
        
        # Execute commands
        if parsed_args.version:
            self.version_command()
        elif parsed_args.status:
            self.status_command()
        elif parsed_args.health:
            self.health_command()
        elif parsed_args.capabilities:
            self.capabilities_command()
        elif parsed_args.info:
            self.info_command()
        elif parsed_args.config:
            self.config_command()
        elif parsed_args.metrics:
            self.metrics_command()
        elif parsed_args.reset:
            self.reset_command()

        else:
            self.help_command()


def main():
    """Main entry point"""
    cli = MakefileHealthManagerCLI()
    cli.run(sys.argv[1:])


if __name__ == '__main__':
    main()
