services:
  observatory:
    environment:
      DISABLE_PROMETHEUS_LEGACY: 'true'
      LOG_LEVEL: INFO
      METRICS_EXPORT_ENABLED: 'true'
      MONITORING_DAEMON_ENABLED: 'false'
      PROMETHEUS_ENABLED: 'true'
      PROMETHEUS_URL: http://observatory-prometheus:9090
version: '3.8'
