#!/usr/bin/env python3
"""
Beast Mode Mailbox Logger Demo

Demonstrates the persistent mailbox logging system that captures
all messages from the Beast Mode network for later retrieval.
"""

import asyncio
import json
import logging
import sys
from datetime import datetime, timedelta
from pathlib import Path

# Add src to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.beast_mode.messaging.mailbox_logger import MailboxLogger, MailboxLoggerManager
from src.beast_mode.messaging.bus_client import BeastModeBusClient
from src.beast_mode.messaging.models import BeastModeMessage, MessageType


# Configure logging
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


async def demo_basic_mailbox_logging():
    """Demonstrate basic mailbox logging functionality"""
    print("\n" + "=" * 60)
    print("DEMO: Basic Mailbox Logging")
    print("=" * 60)

    # Create mailbox logger
    mailbox_logger = MailboxLogger(
        redis_url="redis://localhost:6379",
        log_directory="demo_mailbox_logs",
        channel="beast_mode_network",
        max_log_size_mb=1,  # Small size for demo
        max_log_files=5,
    )

    try:
        print("Starting mailbox logger...")
        await mailbox_logger.start_logging()

        print("✓ Mailbox logger started successfully")
        print(f"✓ Logging to directory: {mailbox_logger.log_directory}")
        print(f"✓ Current log file: {mailbox_logger.current_log_file}")

        # Let it run for a bit to capture any existing messages
        print("\nListening for messages for 3 seconds...")
        await asyncio.sleep(3.0)

        # Check stats
        stats = mailbox_logger.get_logger_stats()
        print(f"\nLogger Statistics:")
        print(f"  Messages logged: {stats['messages_logged']}")
        print(f"  Parsing errors: {stats['parsing_errors']}")
        print(f"  Connection errors: {stats['connection_errors']}")
        print(f"  Runtime: {stats.get('runtime_seconds', 0):.1f} seconds")

        # Get log file information
        log_files = mailbox_logger.get_log_files()
        print(f"\nLog Files ({len(log_files)} total):")
        for log_file in log_files:
            status = " (CURRENT)" if log_file["is_current"] else ""
            print(f"  {Path(log_file['path']).name}: {log_file['size_mb']} MB{status}")

    except Exception as e:
        print(f"✗ Error in mailbox logging: {e}")

    finally:
        print("\nStopping mailbox logger...")
        await mailbox_logger.stop_logging()
        print("✓ Mailbox logger stopped")


async def demo_message_generation_and_logging():
    """Demonstrate logging messages generated by bus clients"""
    print("\n" + "=" * 60)
    print("DEMO: Message Generation and Logging")
    print("=" * 60)

    # Create mailbox logger
    mailbox_logger = MailboxLogger(
        redis_url="redis://localhost:6379",
        log_directory="demo_mailbox_logs",
        channel="beast_mode_network",
    )

    # Create bus clients
    agent1 = BeastModeBusClient(
        redis_url="redis://localhost:6379",
        agent_id="demo_agent_1",
        capabilities=["python", "testing", "demo"],
    )

    agent2 = BeastModeBusClient(
        redis_url="redis://localhost:6379",
        agent_id="demo_agent_2",
        capabilities=["gcp", "terraform", "demo"],
    )

    try:
        # Start mailbox logger
        print("Starting mailbox logger...")
        await mailbox_logger.start_logging()

        # Connect agents
        print("Connecting agents...")
        await agent1.connect()
        await agent2.connect()

        print("✓ All components connected")

        # Generate various types of messages
        print("\nGenerating test messages...")

        # Agent discovery
        await agent1.announce_presence()
        await agent2.announce_presence()
        print("✓ Sent agent discovery messages")

        # Simple messages
        await agent1.send_simple_message("Hello from agent 1!", target="demo_agent_2")
        await agent2.send_simple_message(
            "Hello back from agent 2!", target="demo_agent_1"
        )
        print("✓ Sent simple messages")

        # Help request
        help_request_id = await agent1.send_help_request(
            required_capabilities=["gcp"], description="Need help with GCP deployment"
        )
        print(f"✓ Sent help request: {help_request_id}")

        # Technical exchange
        tech_message = BeastModeMessage(
            type=MessageType.TECHNICAL_EXCHANGE,
            source="demo_agent_1",
            payload={
                "topic": "deployment_config",
                "details": {
                    "environment": "production",
                    "region": "us-central1",
                    "instance_type": "e2-standard-4",
                },
            },
        )
        await agent1.send_message(tech_message)
        print("✓ Sent technical exchange message")

        # Wait for messages to be processed
        print("\nWaiting for messages to be logged...")
        await asyncio.sleep(2.0)

        # Check logger stats
        stats = mailbox_logger.get_logger_stats()
        print(f"\nLogging Results:")
        print(f"  Messages logged: {stats['messages_logged']}")
        print(f"  Parsing errors: {stats['parsing_errors']}")
        print(f"  Last message: {stats['last_message_time']}")

        if stats["messages_logged"] > 0:
            print("✓ Messages successfully logged!")
        else:
            print("⚠ No messages were logged")

    except Exception as e:
        print(f"✗ Error in message generation demo: {e}")

    finally:
        print("\nCleaning up...")
        await agent1.disconnect()
        await agent2.disconnect()
        await mailbox_logger.stop_logging()
        print("✓ All components stopped")


async def demo_mail_checking():
    """Demonstrate checking mail from logged messages"""
    print("\n" + "=" * 60)
    print("DEMO: Mail Checking")
    print("=" * 60)

    # Create mailbox logger (not running, just for reading)
    mailbox_logger = MailboxLogger(log_directory="demo_mailbox_logs")

    try:
        print("Checking mail from logged messages...")

        # Check all messages
        all_messages = await mailbox_logger.check_mail()
        print(f"\nTotal messages in mailbox: {len(all_messages)}")

        if all_messages:
            # Show recent messages
            print("\nRecent messages (last 5):")
            for i, msg_info in enumerate(all_messages[:5]):
                msg = msg_info["message"]
                timestamp = msg_info["log_timestamp"]
                print(f"  {i+1}. [{timestamp}] {msg['type']} from {msg['source']}")
                if msg["type"] == MessageType.SIMPLE_MESSAGE:
                    content = msg["payload"].get("content", "")[:50]
                    print(f"      Content: {content}...")

            # Filter by message type
            simple_messages = await mailbox_logger.check_mail(
                message_types=[MessageType.SIMPLE_MESSAGE]
            )
            print(f"\nSimple messages: {len(simple_messages)}")

            # Filter by source agent
            agent1_messages = await mailbox_logger.check_mail(
                source_agents=["demo_agent_1"]
            )
            print(f"Messages from demo_agent_1: {len(agent1_messages)}")

            # Filter by time (last hour)
            recent_time = datetime.now() - timedelta(hours=1)
            recent_messages = await mailbox_logger.check_mail(since=recent_time)
            print(f"Messages in last hour: {len(recent_messages)}")

            # Limited results
            limited_messages = await mailbox_logger.check_mail(limit=3)
            print(f"Limited to 3 messages: {len(limited_messages)}")

        else:
            print("No messages found in mailbox")
            print("Run the message generation demo first to create some messages")

    except Exception as e:
        print(f"✗ Error checking mail: {e}")


async def demo_detailed_content_saving():
    """Demonstrate saving detailed message content"""
    print("\n" + "=" * 60)
    print("DEMO: Detailed Content Saving")
    print("=" * 60)

    mailbox_logger = MailboxLogger(log_directory="demo_mailbox_logs")

    try:
        # Create a complex message
        complex_message = BeastModeMessage(
            type=MessageType.SPORE_DELIVERY,
            source="demo_agent_1",
            target="demo_agent_2",
            payload={
                "spore_type": "optimization_methodology",
                "spore_content": {
                    "methodology": "systematic_cost_optimization",
                    "steps": [
                        "Analyze current resource usage",
                        "Identify optimization opportunities",
                        "Implement changes systematically",
                        "Monitor and validate improvements",
                    ],
                    "metrics": {
                        "expected_savings": "20-30%",
                        "implementation_time": "2-4 weeks",
                        "risk_level": "low",
                    },
                },
                "metadata": {
                    "version": "1.2.0",
                    "author": "beast_mode_optimizer",
                    "created": datetime.now().isoformat(),
                    "tags": ["cost", "optimization", "gcp", "systematic"],
                },
            },
            priority=2,
        )

        print("Saving detailed content for complex message...")
        content_path = mailbox_logger.save_full_content(complex_message)

        print(f"✓ Detailed content saved to: {content_path}")

        # Read and display the saved content
        with open(content_path, "r") as f:
            saved_content = json.load(f)

        print(f"\nSaved content structure:")
        print(f"  Message ID: {saved_content['message']['id']}")
        print(f"  Message Type: {saved_content['message']['type']}")
        print(f"  Source: {saved_content['message']['source']}")
        print(f"  Payload keys: {list(saved_content['message']['payload'].keys())}")
        print(f"  Saved at: {saved_content['saved_at']}")
        print(f"  Logger stats included: {'logger_stats' in saved_content}")

        # Show spore content preview
        spore_content = saved_content["message"]["payload"]["spore_content"]
        print(f"\nSpore methodology: {spore_content['methodology']}")
        print(f"Steps: {len(spore_content['steps'])}")
        print(f"Expected savings: {spore_content['metrics']['expected_savings']}")

    except Exception as e:
        print(f"✗ Error in detailed content demo: {e}")


def demo_manager_usage():
    """Demonstrate using MailboxLoggerManager for background operation"""
    print("\n" + "=" * 60)
    print("DEMO: Manager Background Operation")
    print("=" * 60)

    try:
        print("Creating MailboxLoggerManager...")

        # Create manager
        manager = MailboxLoggerManager(
            redis_url="redis://localhost:6379",
            log_directory="demo_mailbox_logs",
            channel="beast_mode_network",
        )

        print("✓ Manager created")

        # Test context manager usage
        print("\nUsing manager as context manager...")
        with manager:
            print("✓ Manager started in background")

            # Check status
            status = manager.get_status()
            print(f"  Manager running: {status['manager_running']}")
            print(f"  Thread alive: {status['thread_alive']}")
            print(f"  Logger status: {status['logger_status']['status']}")

            # Simulate some work
            print("  Simulating background operation for 3 seconds...")
            import time

            time.sleep(3)

        print("✓ Manager stopped automatically")

        # Check final status
        final_status = manager.get_status()
        print(f"Final manager running: {final_status['manager_running']}")

    except Exception as e:
        print(f"✗ Error in manager demo: {e}")


async def demo_log_rotation():
    """Demonstrate log rotation functionality"""
    print("\n" + "=" * 60)
    print("DEMO: Log Rotation")
    print("=" * 60)

    # Create logger with very small log size for quick rotation
    mailbox_logger = MailboxLogger(
        redis_url="redis://localhost:6379",
        log_directory="demo_mailbox_logs",
        channel="beast_mode_network",
        max_log_size_mb=0.001,  # 1KB for quick rotation
        max_log_files=3,
        rotation_check_interval=1,  # Check every second
    )

    try:
        print("Starting logger with small log size for rotation demo...")
        await mailbox_logger.start_logging()

        # Create a bus client to generate messages
        agent = BeastModeBusClient(
            redis_url="redis://localhost:6379",
            agent_id="rotation_demo_agent",
            capabilities=["demo", "rotation"],
        )

        await agent.connect()

        print("Generating messages to trigger log rotation...")

        # Send many messages to trigger rotation
        for i in range(20):
            await agent.send_simple_message(
                f"Rotation test message {i} with extra content to make it larger "
                + "and trigger log rotation when the file size limit is reached. "
                + f"Message number {i} of 20 total messages for rotation testing."
            )

            if i % 5 == 0:
                print(f"  Sent {i+1} messages...")

            await asyncio.sleep(0.1)

        # Wait for rotation to be processed
        print("Waiting for log rotation to complete...")
        await asyncio.sleep(3.0)

        # Check rotation results
        stats = mailbox_logger.get_logger_stats()
        log_files = mailbox_logger.get_log_files()

        print(f"\nRotation Results:")
        print(f"  Messages logged: {stats['messages_logged']}")
        print(f"  Log rotations: {stats['log_rotations']}")
        print(f"  Total log files: {len(log_files)}")

        print(f"\nLog Files:")
        for log_file in log_files:
            status = " (CURRENT)" if log_file["is_current"] else ""
            print(f"  {Path(log_file['path']).name}: {log_file['size_mb']} MB{status}")

        if stats["log_rotations"] > 0:
            print("✓ Log rotation occurred successfully!")
        else:
            print("⚠ No log rotation occurred (file size may not have exceeded limit)")

    except Exception as e:
        print(f"✗ Error in rotation demo: {e}")

    finally:
        await agent.disconnect()
        await mailbox_logger.stop_logging()


async def main():
    """Run all mailbox logger demos"""
    print("Beast Mode Mailbox Logger Demo")
    print("==============================")
    print("This demo shows the persistent message logging system")
    print("that captures all Beast Mode network messages for later retrieval.")

    try:
        # Run demos in sequence
        await demo_basic_mailbox_logging()
        await demo_message_generation_and_logging()
        await demo_mail_checking()
        await demo_detailed_content_saving()
        demo_manager_usage()
        await demo_log_rotation()

        print("\n" + "=" * 60)
        print("ALL DEMOS COMPLETED SUCCESSFULLY!")
        print("=" * 60)
        print(
            "\nCheck the 'demo_mailbox_logs' directory to see the generated log files."
        )
        print(
            "You can also run individual demo functions to explore specific features."
        )

    except KeyboardInterrupt:
        print("\n\nDemo interrupted by user")
    except Exception as e:
        print(f"\n✗ Demo failed with error: {e}")
        import traceback

        traceback.print_exc()


if __name__ == "__main__":
    # Run the demo
    asyncio.run(main())
