"""
Observatory Core Engine - Central orchestrator for the Beast Mode Coordination Observatory.

This module provides the main coordination engine that manages all Observatory functionality,
from metrics collection to real-time visualization and cultural reinforcement.
"""

import asyncio
import logging
from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional

from ..core import ReflectiveModule
from .models import (
    ObservatoryConfig,
    CoordinationEvent,
    CoordinationMetrics,
    HealthScore,
    CostMetrics,
    Anomaly,
    Achievement,
)


logger = logging.getLogger(__name__)


@dataclass
class ObservatoryInsights:
    """Real-time insights generated by the Observatory."""
    timestamp: datetime = field(default_factory=datetime.now)
    coordination_health: HealthScore = field(default_factory=lambda: HealthScore(overall_score=1.0))
    cost_summary: CostMetrics = field(default_factory=CostMetrics)
    active_anomalies: List[Anomaly] = field(default_factory=list)
    recent_achievements: List[Achievement] = field(default_factory=list)
    system_recommendations: List[str] = field(default_factory=list)


class ObservatoryCoreEngine(ReflectiveModule):
    """Central orchestrator for the Beast Mode Coordination Observatory."""
    
    def __init__(self, config: ObservatoryConfig):
        super().__init__()
        self.module_id = "observatory_core"
        self._config = config
        self._running = False
        self._tasks: List[asyncio.Task] = []
        
        # Initialize components
        self._metrics_collector = None
        self._cost_tracker = None
        self._analytics_engine = None
        self._websocket_server = None
        self._anomaly_detector = None
        self._gamification_engine = None
        
        logger.info(f"Observatory Core Engine initialized with config: {config}")
    
    async def start_observatory(self) -> bool:
        """Start all Observatory components and begin monitoring."""
        try:
            if self._running:
                logger.warning("Observatory is already running")
                return True
            
            logger.info("Starting Beast Mode Coordination Observatory...")
            
            # Validate configuration
            if not self._config.validate():
                logger.error("Invalid Observatory configuration")
                return False
            
            # Initialize and start MetricsCollector
            from .metrics_collector import MetricsCollector
            self._metrics_collector = MetricsCollector(self._config)
            await self._metrics_collector.start_collection()
            
            # Initialize and start LLMCostTracker
            from .llm_cost_tracker import LLMCostTracker
            self._cost_tracker = LLMCostTracker(self._config)
            await self._cost_tracker.start_tracking()
            
            # Initialize and start RealTimeAnalyticsEngine
            from .analytics_engine import RealTimeAnalyticsEngine
            self._analytics_engine = RealTimeAnalyticsEngine(self._config)
            await self._analytics_engine.start_analytics()

            # Initialize and start AnomalyDetectionEngine
            from .anomaly_detection import AnomalyDetectionEngine
            self._anomaly_detector = AnomalyDetectionEngine(self._config)
            await self._anomaly_detector.start_detection()

            # Start core monitoring loop
            self._running = True
            monitoring_task = asyncio.create_task(self._monitoring_loop())
            self._tasks.append(monitoring_task)
            
            logger.info("Observatory started successfully")
            return True
            
        except Exception as e:
            logger.error(f"Failed to start Observatory: {e}")
            return False
    
    async def stop_observatory(self) -> None:
        """Stop all Observatory components gracefully."""
        logger.info("Stopping Beast Mode Coordination Observatory...")
        
        self._running = False
        
        # Stop MetricsCollector
        if self._metrics_collector:
            await self._metrics_collector.stop_collection()
        
        # Stop LLMCostTracker
        if self._cost_tracker:
            await self._cost_tracker.stop_tracking()
        
        # Stop RealTimeAnalyticsEngine
        if self._analytics_engine:
            await self._analytics_engine.stop_analytics()

        # Stop AnomalyDetectionEngine
        if self._anomaly_detector:
            await self._anomaly_detector.stop_detection()

        # Cancel all running tasks
        for task in self._tasks:
            if not task.done():
                task.cancel()
        
        # Wait for tasks to complete
        if self._tasks:
            await asyncio.gather(*self._tasks, return_exceptions=True)
        
        self._tasks.clear()
        logger.info("Observatory stopped successfully")
    
    async def process_coordination_event(self, event: CoordinationEvent) -> None:
        """Process incoming coordination events and update displays."""
        try:
            logger.debug(f"Processing coordination event: {event.event_type} from {event.source_component}")
            
            # TODO: Route event to appropriate processors
            # - Analytics engine for trend analysis
            # - Anomaly detector for pattern analysis
            # - Gamification engine for achievement tracking
            # - WebSocket server for real-time updates
            
            # For now, just log the event
            logger.info(f"Processed event {event.event_id}: {event.event_type}")
            
        except Exception as e:
            logger.error(f"Error processing coordination event {event.event_id}: {e}")
    
    async def generate_real_time_insights(self) -> ObservatoryInsights:
        """Generate real-time insights for dashboard display."""
        try:
            insights = ObservatoryInsights()
            
            # Get metrics from MetricsCollector if available
            if self._metrics_collector:
                collector_metrics = await self._metrics_collector.get_metrics()
                insights.system_recommendations.append(
                    f"Discovered {collector_metrics.get('discovered_components', 0)} Beast Mode components"
                )
                
                collection_stats = collector_metrics.get('collection_stats', {})
                if collection_stats.get('error_rate_percent', 0) > 5:
                    insights.system_recommendations.append(
                        f"Metrics collection error rate: {collection_stats.get('error_rate_percent', 0):.1f}%"
                    )
            
            logger.debug("Generated real-time insights")
            return insights
            
        except Exception as e:
            logger.error(f"Error generating insights: {e}")
            return ObservatoryInsights()
    
    async def _monitoring_loop(self) -> None:
        """Main monitoring loop that coordinates all Observatory activities."""
        logger.info("Starting Observatory monitoring loop")
        
        while self._running:
            try:
                # Generate and process insights
                insights = await self.generate_real_time_insights()
                
                # TODO: Broadcast insights to connected clients
                # TODO: Check for anomalies and alerts
                # TODO: Update gamification metrics
                
                # Sleep for the configured interval
                await asyncio.sleep(self._config.metrics_config.collection_interval_seconds)
                
            except asyncio.CancelledError:
                logger.info("Observatory monitoring loop cancelled")
                break
            except Exception as e:
                logger.error(f"Error in Observatory monitoring loop: {e}")
                # Continue running even if there's an error
                await asyncio.sleep(1)
        
        logger.info("Observatory monitoring loop stopped")
    
    # ReflectiveModule implementation
    
    def get_capabilities(self) -> List['ModuleCapability']:
        """Get Observatory module capabilities."""
        from src.rm_ddd.core.unified_reflective_module import ModuleCapability
        return [
            ModuleCapability.MONITORING,
            ModuleCapability.DATA_PROCESSING,
            ModuleCapability.API_INTEGRATION,
        ]
    
    def get_health_status(self) -> 'ModuleHealth':
        """Get health status of the Observatory."""
        from src.rm_ddd.core.unified_reflective_module import ModuleHealth, ModuleStatus
        
        # Determine status based on running state and component health
        if self._running:
            status = ModuleStatus.HEALTHY
            health_score = 1.0
            issues = []
        else:
            status = ModuleStatus.ERROR
            health_score = 0.0
            issues = ["Observatory is not running"]
        
        # Check configuration validity
        if not self._config.validate():
            status = ModuleStatus.ERROR
            health_score = 0.0
            issues.append("Invalid configuration")
        
        uptime = (datetime.now() - self._start_time).total_seconds()
        
        return ModuleHealth(
            module_id=self.module_id,
            status=status,
            health_score=health_score,
            issues=issues,
            last_check=datetime.now(),
            uptime_seconds=uptime,
            error_count=self._error_count,
            warning_count=self._warning_count
        )
    
    def graceful_degradation(self) -> 'GracefulDegradationResult':
        """Perform graceful degradation of Observatory functionality."""
        from src.rm_ddd.core.unified_reflective_module import (
            GracefulDegradationResult, 
            ModuleCapability
        )
        
        try:
            # In degraded mode, we can still monitor but with reduced functionality
            degraded_capabilities = []
            remaining_capabilities = [
                ModuleCapability.MONITORING,
                ModuleCapability.DATA_PROCESSING,
            ]
            
            # If Redis is unavailable, we lose API integration capability
            if not self._config.redis_config:
                degraded_capabilities.append(ModuleCapability.API_INTEGRATION)
                remaining_capabilities = [ModuleCapability.MONITORING]
            
            return GracefulDegradationResult(
                success=True,
                degraded_capabilities=degraded_capabilities,
                remaining_capabilities=remaining_capabilities
            )
            
        except Exception as e:
            return GracefulDegradationResult(
                success=False,
                degraded_capabilities=[],
                remaining_capabilities=[],
                error_message=str(e)
            )
    
    async def get_metrics(self) -> Dict[str, any]:
        """Get Observatory performance metrics."""
        return {
            "observatory_uptime_seconds": (datetime.now() - self._start_time).total_seconds(),
            "events_processed_total": 0,      # TODO: Track processed events
            "insights_generated_total": 0,    # TODO: Track generated insights
            "active_connections": 0,          # TODO: Track WebSocket connections
            "memory_usage_mb": 0,            # TODO: Track memory usage
        }
    
    def get_module_info(self) -> Dict[str, any]:
        """Get Observatory module information."""
        return {
            "module_id": self.module_id,
            "name": "Beast Mode Coordination Observatory",
            "version": "1.0.0",
            "description": "Real-time coordination monitoring with cultural reinforcement",
            "config": {
                "redis_host": self._config.redis_config.host,
                "websocket_port": self._config.websocket_config.port,
                "metrics_interval": self._config.metrics_config.collection_interval_seconds,
                "emoji_rain_enabled": self._config.gamification_config.emoji_rain_enabled,
            }
        }