from .health_class_3_part_1 import *
from .health_class_3_part_2 import *
from .health_class_3_part_3 import *
from .health_class_3_part_4 import *
from .health_class_3_part_5 import *
from .health_class_3_part_6 import *
from .health_class_3_part_7 import *
from .health_class_3_part_8 import *
from .health_class_3_part_9 import *
from .health_class_3_part_10 import *
from .health_class_3_part_11 import *
from .health_class_3_part_12 import *
from .health_class_3_part_13 import *
from .health_class_3_part_14 import *
from .health_class_3_part_15 import *
from .health_class_3_part_16 import *
from .health_class_3_part_17 import *
from .health_class_3_part_18 import *
from .health_class_3_part_19 import *
from .health_class_3_part_20 import *
from .health_class_3_part_21 import *
from .health_class_3_part_22 import *
from .health_class_3_part_23 import *
from .health_class_3_part_24 import *
from .health_class_3_part_25 import *
from .health_class_3_part_26 import *
from .health_class_3_part_27 import *
from .health_class_3_part_28 import *
from .health_class_3_part_29 import *
from .health_class_3_part_30 import *
from .health_class_3_part_31 import *
from .health_class_3_part_32 import *
from .health_class_3_part_33 import *
from .health_class_3_part_34 import *
from .health_class_3_part_35 import *
from .health_class_3_part_36 import *
from .health_class_3_part_37 import *
from .health_class_3_part_38 import *