from .manager_services_core_core_part_1 import *
from .manager_services_core_core_part_2 import *
from .manager_services_core_core_part_3 import *
from .manager_services_core_core_part_4 import *
from .manager_services_core_core_part_5 import *
from .manager_services_core_core_part_6 import *
from .manager_services_core_core_part_7 import *
from .manager_services_core_core_part_8 import *
from .manager_services_core_core_part_9 import *
from .manager_services_core_core_part_10 import *
from .manager_services_core_core_part_11 import *
from .manager_services_core_core_part_12 import *
from .manager_services_core_core_part_13 import *
from .manager_services_core_core_part_14 import *
from .manager_services_core_core_part_15 import *
from .manager_services_core_core_part_16 import *
from .manager_services_core_core_part_17 import *
from .manager_services_core_core_part_18 import *
from .manager_services_core_core_part_19 import *
from .manager_services_core_core_part_20 import *
from .manager_services_core_core_part_21 import *