#!/bin/bash
# Grafana Access Helper Script

echo "🎯 Grafana Access Information"
echo "=============================="
echo ""
echo "🌐 Direct Access URLs:"
echo "  Main Dashboard: http://localhost:3000"
echo "  Beast Mode Dashboard: http://localhost:3000/d/770bf50d-fe07-4368-829c-dec6bf8db739/beast-mode-framework"
echo ""
echo "🔑 Login Credentials:"
echo "  Username: admin"
echo "  Password: systematic"
echo ""
echo "📊 Available Dashboards:"
echo "  - Beast Mode Framework (Time Series Graphs)"
echo "  - Prometheus Data Source (Connected)"
echo ""
echo "🔧 Quick Commands:"
echo "  Open Grafana: open http://localhost:3000"
echo "  Open Beast Mode Dashboard: open http://localhost:3000/d/770bf50d-fe07-4368-829c-dec6bf8db739/beast-mode-framework"
echo "  Check Health: curl -u admin:systematic http://localhost:3000/api/health"
echo ""
echo "📈 Time Series Graphs Available:"
echo "  - Beast Mode Status (Real-time health)"
echo "  - Uptime Over Time (System uptime trends)"
echo "  - Platform Information (macOS system info)"
echo "  - Request Count (API request metrics)"
echo "  - Restricted Mode Status (Walled garden indicator)"
echo "  - Metrics Availability (System operational status)"
echo ""
echo "🔄 Live Data:"
echo "  - Refresh Rate: Every 5 seconds"
echo "  - Time Range: Last 1 hour (adjustable)"
echo "  - Data Source: Prometheus (http://prometheus:9090)"
echo ""
echo "🚀 Ready to monitor your Beast Mode framework!"
