from .devpostmediadetector_interface_part_1 import *
from .devpostmediadetector_interface_part_2 import *
from .devpostmediadetector_interface_part_3 import *
from .devpostmediadetector_interface_part_4 import *
from .devpostmediadetector_interface_part_5 import *
from .devpostmediadetector_interface_part_6 import *
from .devpostmediadetector_interface_part_7 import *
from .devpostmediadetector_interface_part_8 import *
from .devpostmediadetector_interface_part_9 import *
from .devpostmediadetector_interface_part_10 import *
from .devpostmediadetector_interface_part_11 import *
from .devpostmediadetector_interface_part_12 import *
from .devpostmediadetector_interface_part_13 import *
from .devpostmediadetector_interface_part_14 import *
from .devpostmediadetector_interface_part_15 import *
from .devpostmediadetector_interface_part_16 import *
from .devpostmediadetector_interface_part_17 import *
from .devpostmediadetector_interface_part_18 import *
from .devpostmediadetector_interface_part_19 import *