"""
QueuedSyncOperation Interface

Authoritative interface definition for QueuedSyncOperation.
Consolidated from multiple duplicate definitions.

Generated by Interface Consolidation System.
"""

import logging
from datetime import datetime
from ..devpost_integration.reflective_module import ReflectiveModule, register_module, ModuleHealth, ModuleStatus, ModuleCapability
from typing import Dict, List, Any, Optional

class QueuedSyncOperation(ReflectiveModule):
    """Represents a queued sync operation."""
    operation_id: str
    priority: SyncPriority
    operation_type: str
    created_at: datetime
    retry_count: int = 0


@dataclass
