from .beast_mode_system_part_1 import *
from .beast_mode_system_part_2 import *
from .beast_mode_system_part_3 import *
from .beast_mode_system_part_4 import *
from .beast_mode_system_part_5 import *
from .beast_mode_system_part_6 import *
from .beast_mode_system_part_7 import *
from .beast_mode_system_part_8 import *
from .beast_mode_system_part_9 import *
from .beast_mode_system_part_10 import *
from .beast_mode_system_part_11 import *
from .beast_mode_system_part_12 import *
from .beast_mode_system_part_13 import *
from .beast_mode_system_part_14 import *
from .beast_mode_system_part_15 import *
from .beast_mode_system_part_16 import *
from .beast_mode_system_part_17 import *
from .beast_mode_system_part_18 import *
from .beast_mode_system_part_19 import *
from .beast_mode_system_part_20 import *
from .beast_mode_system_part_21 import *
from .beast_mode_system_part_22 import *
from src.rm_ddd.core.health import ModuleHealth
