from .execution_strategy_part_1 import *
from .execution_strategy_part_2 import *
from .execution_strategy_part_3 import *
from .execution_strategy_part_4 import *
from .execution_strategy_part_5 import *
from .execution_strategy_part_6 import *
from .execution_strategy_part_7 import *
from .execution_strategy_part_8 import *
from .execution_strategy_part_9 import *
from .execution_strategy_part_10 import *
from .execution_strategy_part_11 import *
from .execution_strategy_part_12 import *
from .execution_strategy_part_13 import *
from .execution_strategy_part_14 import *
from .execution_strategy_part_15 import *
from .execution_strategy_part_16 import *
from .execution_strategy_part_17 import *
from .execution_strategy_part_18 import *
from .execution_strategy_part_19 import *
from .execution_strategy_part_20 import *
from .execution_strategy_part_21 import *
from .execution_strategy_part_22 import *
from .execution_strategy_part_23 import *
from .execution_strategy_part_24 import *
from .execution_strategy_part_25 import *
from .execution_strategy_part_26 import *
from .execution_strategy_part_27 import *
from .execution_strategy_part_28 import *
from .execution_strategy_part_29 import *
from .execution_strategy_part_30 import *
from .execution_strategy_part_31 import *
from .execution_strategy_part_32 import *