from .health_dashboard_part_1 import *
from .health_dashboard_part_2 import *
from .health_dashboard_part_3 import *
from .health_dashboard_part_4 import *
from .health_dashboard_part_5 import *
from .health_dashboard_part_6 import *
from .health_dashboard_part_7 import *
from .health_dashboard_part_8 import *
from .health_dashboard_part_9 import *
from .health_dashboard_part_10 import *
from .health_dashboard_part_11 import *
from .health_dashboard_part_12 import *
from .health_dashboard_part_13 import *
from .health_dashboard_part_14 import *
from .health_dashboard_part_15 import *
from .health_dashboard_part_16 import *
from .health_dashboard_part_17 import *
from .health_dashboard_part_18 import *
from .health_dashboard_part_19 import *
from .health_dashboard_part_20 import *
from .health_dashboard_part_21 import *