"""
Cli Core

This module was extracted from cli.py
as part of RM-DDD compliance refactoring.
"""

import asyncio
import json
import logging
from pathlib import Path
from typing import Optional
import click
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.syntax import Syntax
from . import __version__, get_ecosystem_info, quick_start_example
from .core.registry import get_global_registry
from .core.compliance import get_global_compliance_orchestrator
import webbrowser

@click.group()
@click.version_option(version=__version__)
@click.option('--verbose', '-v', is_flag=True, help='Enable verbose logging')
def main(verbose: bool):
    """RM-DDD SDK: Systematic Domain-Driven Development Framework"""
    if verbose:
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)

@main.command()
def info():
    """Display ecosystem information"""
    ecosystem_info = get_ecosystem_info()
    console.print(Panel.fit(f"[bold blue]RM-DDD SDK v{ecosystem_info['rm_ddd_version']}[/bold blue]\n[italic]{ecosystem_info['philosophy']}[/italic]", title='Beast Mode Ecosystem'))
    table = Table(title='Ecosystem Components')
    table.add_column('Component', style='cyan')
    table.add_column('Description', style='white')
    component_descriptions = {'Beast Mode Framework': 'Systematic development methodology with PDCA cycles', 'Ghostbusters AI Agents': 'Multi-agent system for intelligent code analysis', 'Spec-to-Code Engine': 'Automated transformation from specs to code', 'Intelligent Quality System': 'AI-powered validation with >90% coverage', 'RM Registry': 'Component discovery and health monitoring'}
    for component in ecosystem_info['ecosystem_components']:
        description = component_descriptions.get(component, 'Core ecosystem component')
        table.add_row(component, description)
    console.print(table)
    console.print(f"\n[bold]Documentation:[/bold] {ecosystem_info['documentation']}")
    console.print(f"[bold]Ecosystem Guide:[/bold] {ecosystem_info['ecosystem_docs']}")

@main.command()
def quickstart():
    """Display quick start example"""
    example_code = quick_start_example()
    console.print(Panel('This example shows how to create a domain entity with systematic validation:', title='Quick Start Example'))
    syntax = Syntax(example_code, 'python', theme='monokai', line_numbers=True)
    console.print(syntax)
    console.print('\n[bold green]Next Steps:[/bold green]')
    console.print('1. Install: [cyan]pip install rm-ddd[/cyan]')
    console.print('2. Copy the example above to get started')
    console.print('3. Read the docs: [cyan]https://rm-ddd.readthedocs.io/[/cyan]')

@main.command()
@click.argument('entity_name')
@click.argument('domain_context')
@click.option('--output-dir', '-o', type=click.Path(), default='.', help='Output directory')
def generate_entity(entity_name: str, domain_context: str, output_dir: str):
    """Generate a domain entity class"""
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    entity_code = f'"""\n{entity_name} domain entity.\n\nGenerated by RM-DDD SDK.\n"""\n\nfrom typing import Any, Dict, List\nfrom rm_ddd import Entity, DomainBoundaries, ValidationResult\nfrom rm_ddd.decorators import domain_entity\n\n\n@domain_entity("{domain_context}")\nclass {entity_name}(Entity[str]):\n    """\n    {entity_name} domain entity.\n    \n    TODO: Add entity description and business rules.\n    """\n    \n    def __init__(self, entity_id: str):\n        super().__init__(entity_id, "{domain_context}")\n        # TODO: Add entity attributes\n    \n    def get_domain_boundaries(self) -> DomainBoundaries:\n        """Define {entity_name} domain boundaries."""\n        return DomainBoundaries(\n            context="{domain_context}",\n            invariants=[\n                # TODO: Add domain invariants\n                "entity_id_not_empty"\n            ],\n            ubiquitous_language={{\n                # TODO: Add ubiquitous language mappings\n            }}\n        )\n    \n    def validate_domain_invariants(self) -> ValidationResult:\n        """Validate {entity_name} domain invariants."""\n        result = ValidationResult(is_valid=True)\n        \n        # Basic validation\n        if not self.id or not str(self.id).strip():\n            result.add_error("Entity ID cannot be empty")\n        \n        # TODO: Add specific domain invariant validations\n        \n        return result\n'
    file_path = output_path / f'{entity_name.lower()}.py'
    with open(file_path, 'w') as f:
        f.write(entity_code)
    console.print(f'[green]Generated entity: {file_path}[/green]')
    console.print(f'[yellow]TODO: Customize the generated entity with your business logic[/yellow]')

@main.command()
def docs():
    """Open documentation in browser"""
    import webbrowser
    docs_url = 'https://rm-ddd.readthedocs.io/'
    console.print(f'Opening documentation: {docs_url}')
    webbrowser.open(docs_url)

def async_command(f):
    """Decorator to run async commands"""

    def wrapper(*args, **kwargs):
        return asyncio.run(f(*args, **kwargs))
    return wrapper

def wrapper(*args, **kwargs):
    return asyncio.run(f(*args, **kwargs))
